version: '3.4'

services:
  concord:
    build: .
    container_name: concord
    restart: unless-stopped
  nginx:
    container_name: nginx
    depends_on:
      - concord
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/dhparam:/etc/nginx/dhparam
