version: '3.4'

services:
  concord:
    build: .
    container_name: concord
    environment:
      - DEBUG=
    image: concord:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./src:/concord
