# Generated by Django 2.0.2 on 2018-02-19 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concord', '0002_auto_20180219_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCryptoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_symetric_key', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='encrypted_symetric_key',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='users',
            field=models.ManyToManyField(through='concord.ChatCryptoInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatcryptoinfo',
            name='chatGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concord.ChatGroup'),
        ),
        migrations.AddField(
            model_name='chatcryptoinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
