# Generated by Django 2.0.2 on 2018-02-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concord', '0003_auto_20180219_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcryptoinfo',
            old_name='user',
            new_name='concordUser',
        ),
    ]
