# Generated by Django 2.0.2 on 2018-02-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concord', '0004_auto_20180219_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='users',
        ),
        migrations.RemoveField(
            model_name='concorduser',
            name='encrypted_private_key',
        ),
    ]
